# Generated by Django 4.1.4 on 2022-12-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('name', models.CharField(max_length=64, verbose_name='category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'main_categories',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(max_length=20, verbose_name='week day')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='opening time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='closing time')),
            ],
            options={
                'verbose_name': 'work schedule',
                'verbose_name_plural': 'work schedules',
                'db_table': 'main_work_schedule',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('name', models.CharField(max_length=64, verbose_name='product')),
                ('image', models.ImageField(upload_to='products/', verbose_name='picture')),
                ('descr', models.CharField(max_length=3000, verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'main_products',
            },
        ),
    ]
